name: Tests

on: 
  workflow_dispatch:
  
jobs:
  run-on-803:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.303

    - name: update global.json
      run: echo '{"sdk": {"version": "8.0.303"}}' > global.json


    - name: Build
      run: dotnet build

    - name: Run tests
      run: cd EquateRecordsAssembly; dotnet run


  run-on-804:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.401

    - name: update global.json
      run: echo '{"sdk": {"version": "8.0.401"}}' > global.json

    - name: Build
      run: dotnet build

    - name: Run tests
      run: cd EquateRecordsAssembly; dotnet run


